-- seeds.sql
-- Dados iniciais para simulação abrangente da B3

-- 1. Inserir configurações do sistema
INSERT INTO public.system_config (key, value) VALUES
('market_status', 'open'),
('sell_commission', '0.00025')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 2. Inserir cotações iniciais de ~115 ativos da B3 (Ações, FIIs e ETFs)
-- OBS: O robô de sincronização atualizará esses valores para as cotações exatas em tempo de execução.
INSERT INTO public.assets (symbol, name, type, last_price, updated_at) VALUES
-- Ações (Ibovespa / Principais do Mercado)
('ABEV3', 'Ambev S.A.', 'acao', 12.50, now()),
('ALOS3', 'Allos S.A.', 'acao', 22.10, now()),
('ALPA4', 'Alpargatas S.A.', 'acao', 9.20, now()),
('ARZZ3', 'Arezzo Indústria e Comércio S.A.', 'acao', 58.40, now()),
('ASAI3', 'Sendas Distribuidora S.A. - Assaí', 'acao', 13.10, now()),
('AZUL4', 'Azul S.A.', 'acao', 11.80, now()),
('B3SA3', 'B3 S.A. - Brasil, Bolsa, Balcão', 'acao', 12.20, now()),
('BBAS3', 'Banco do Brasil S.A.', 'acao', 27.50, now()),
('BBDC3', 'Banco Bradesco S.A. Ord', 'acao', 12.80, now()),
('BBDC4', 'Banco Bradesco S.A. Pref', 'acao', 14.50, now()),
('BBSE3', 'BB Seguridade Participações S.A.', 'acao', 33.10, now()),
('BEEF3', 'Minerva S.A.', 'acao', 7.40, now()),
('BPAC11', 'Banco BTG Pactual S.A.', 'acao', 36.80, now()),
('BRAP4', 'Bradespar S.A.', 'acao', 20.30, now()),
('BRFS3', 'BRF S.A.', 'acao', 15.60, now()),
('BRKM5', 'Braskem S.A.', 'acao', 19.80, now()),
('CCRO3', 'CCR S.A.', 'acao', 13.40, now()),
('CIEL3', 'Cielo S.A.', 'acao', 5.60, now()),
('CMIG4', 'Companhia Energética de Minas Gerais', 'acao', 11.20, now()),
('COGN3', 'Cogna Educação S.A.', 'acao', 2.30, now()),
('CPFE3', 'CPFL Energia S.A.', 'acao', 35.40, now()),
('CPLE6', 'Companhia Paranaense de Energia', 'acao', 9.80, now()),
('CRFB3', 'Carrefour Brasil S.A.', 'acao', 10.90, now()),
('CSAN3', 'Cosan S.A.', 'acao', 15.20, now()),
('CSNA3', 'Companhia Siderúrgica Nacional', 'acao', 14.80, now()),
('CYRE3', 'Cyrela Brazil Realty S.A.', 'acao', 21.50, now()),
('DXCO3', 'Dexco S.A.', 'acao', 7.80, now()),
('EGIE3', 'Engie Brasil Energia S.A.', 'acao', 42.10, now()),
('ELET3', 'Centrais Elétricas Brasileiras S.A.', 'acao', 38.50, now()),
('ELET6', 'Centrais Elétricas Brasileiras Pref', 'acao', 44.20, now()),
('EMBR3', 'Embraer S.A.', 'acao', 24.10, now()),
('ENEV3', 'Eneva S.A.', 'acao', 12.80, now()),
('ENGI11', 'Energisa S.A.', 'acao', 48.50, now()),
('EQTL3', 'Equatorial Energia S.A.', 'acao', 31.20, now()),
('EZTC3', 'EZTEC Empreendimentos e Participações S.A.', 'acao', 15.80, now()),
('FLRY3', 'Fleury S.A.', 'acao', 16.20, now()),
('GGBR4', 'Gerdau S.A.', 'acao', 21.50, now()),
('GOAU4', 'Metalúrgica Gerdau S.A.', 'acao', 10.40, now()),
('GOLL4', 'Gol Linhas Aéreas Inteligentes S.A.', 'acao', 2.80, now()),
('HAPV3', 'Hapvida Participações e Investimentos S.A.', 'acao', 3.90, now()),
('HYPE3', 'Hypera S.A.', 'acao', 34.50, now()),
('IGTI11', 'Iguatemi S.A.', 'acao', 22.80, now()),
('IRBR3', 'IRB - Brasil Resseguros S.A.', 'acao', 39.50, now()),
('ITSA4', 'Itaúsa S.A.', 'acao', 9.80, now()),
('ITUB4', 'Itaú Unibanco Holding S.A.', 'acao', 32.80, now()),
('JBSS3', 'JBS S.A.', 'acao', 22.10, now()),
('JHSF3', 'JHSF Participações S.A.', 'acao', 4.50, now()),
('KLBN11', 'Klabin S.A.', 'acao', 21.90, now()),
('LREN3', 'Lojas Renner S.A.', 'acao', 16.50, now()),
('MDIA3', 'M. Dias Branco S.A.', 'acao', 36.20, now()),
('MGLU3', 'Magazine Luiza S.A.', 'acao', 2.10, now()),
('MRFG3', 'Marfrig Global Foods S.A.', 'acao', 9.50, now()),
('MRVE3', 'MRV Engenharia e Participações S.A.', 'acao', 7.20, now()),
('MULT3', 'Multiplan Empreendimentos Imobiliários S.A.', 'acao', 24.80, now()),
('NTCO3', 'Natura &Co Holding S.A.', 'acao', 15.90, now()),
('ODPV3', 'Odontoprev S.A.', 'acao', 11.80, now()),
('PETR3', 'Petróleo Brasileiro S.A. Ord', 'acao', 40.50, now()),
('PETR4', 'Petróleo Brasileiro S.A. Pref', 'acao', 42.09, now()),
('PRIO3', 'PetroRio S.A.', 'acao', 44.50, now()),
('RADL3', 'Raia Drogasil S.A.', 'acao', 26.20, now()),
('RAIZ4', 'Raízen S.A.', 'acao', 3.60, now()),
('RECV3', 'PetroReconcavo S.A.', 'acao', 21.10, now()),
('RENT3', 'Localiza Rent a Car S.A.', 'acao', 58.40, now()),
('SANB11', 'Banco Santander (Brasil) S.A.', 'acao', 28.50, now()),
('SBSP3', 'Companhia de Saneamento Básico do Estado de SP', 'acao', 78.20, now()),
('SLCE3', 'SLC Agrícola S.A.', 'acao', 19.10, now()),
('SMTO3', 'São Martinho S.A.', 'acao', 29.50, now()),
('SUZB3', 'Suzano S.A.', 'acao', 56.40, now()),
('TAEE11', 'Transmissora Aliança de Energia Elétrica S.A.', 'acao', 35.80, now()),
('TIMS3', 'TIM S.A.', 'acao', 17.20, now()),
('TOTS3', 'Totvs S.A.', 'acao', 30.10, now()),
('TRPL4', 'CTEEP - Companhia de Transmissão de Energia Pref', 'acao', 25.10, now()),
('UGPA3', 'Ultrapar Participações S.A.', 'acao', 26.40, now()),
('USIM5', 'Usinas Siderúrgicas de Minas Gerais Pref', 'acao', 8.20, now()),
('VALE3', 'Vale S.A.', 'acao', 62.10, now()),
('VIVT3', 'Telefônica Brasil S.A.', 'acao', 51.50, now()),
('WEGE3', 'WEG S.A.', 'acao', 38.50, now()),
('YDUQ3', 'YDUQS Participações S.A.', 'acao', 16.80, now()),

-- FIIs (Fundos Imobiliários de Alta Liquidez)
('MXRF11', 'Maxi Renda FII', 'fii', 10.15, now()),
('HGLG11', 'CSHG Logística FII', 'fii', 165.00, now()),
('ALZR11', 'Alianza Trust Renda Imobiliária FII', 'fii', 115.00, now()),
('HGRU11', 'CSHG Renda Urbana FII', 'fii', 125.00, now()),
('XPLG11', 'XP Log FII', 'fii', 108.50, now()),
('XPML11', 'XP Malls FII', 'fii', 112.40, now()),
('KNIP11', 'Kinea Índices de Preços FII', 'fii', 98.20, now()),
('KNCR11', 'Kinea Rendimentos Imobiliários FII', 'fii', 102.50, now()),
('HFOF11', 'Hedge Top FOFII FII', 'fii', 74.50, now()),
('VISC11', 'Vinci Shopping Centers FII', 'fii', 118.20, now()),
('BRCO11', 'Bresco Logística FII', 'fii', 122.50, now()),
('MALL11', 'Malls Brasil Plural FII', 'fii', 114.10, now()),
('BTLG11', 'BTG Pactual Logística FII', 'fii', 102.80, now()),
('PVBI11', 'VBI Prime Offices FII', 'fii', 98.40, now()),
('JSRE11', 'JS Real Estate Multigestão FII', 'fii', 72.10, now()),
('RECR11', 'FII Rec Recebíveis Imobiliários', 'fii', 82.50, now()),
('HGCR11', 'CSHG Recebíveis Imobiliários FII', 'fii', 104.20, now()),
('CPTS11', 'Capitânia Securities II FII', 'fii', 8.20, now()),
('TGAR11', 'TG Ativa Real FII', 'fii', 121.50, now()),
('IRDM11', 'Iridium Recebíveis Imobiliários FII', 'fii', 78.40, now()),

-- ETFs (Fundos de Índice e BDRs de Ações Globais)
('BOVA11', 'iShares Ibovespa Fundo de Índice', 'etf', 122.00, now()),
('IVVB11', 'iShares S&P 500 Fundo de Índice BDR', 'etf', 280.00, now()),
('SMAL11', 'iShares BM&FBOVESPA Small Cap FII', 'etf', 105.40, now()),
('XINA11', 'Trend China MSCI Fundo de Índice', 'etf', 6.20, now()),
('HASH11', 'Hashdex Nasdaq Crypto Index ETF', 'etf', 48.50, now()),
('QBTC11', 'QR Bitcoin ETF', 'etf', 16.80, now()),
('QETH11', 'QR Ether ETF', 'etf', 8.50, now()),
('DIVO11', 'Itau Ibovespa Div/IDIV Fundo de Índice', 'etf', 84.10, now())
ON CONFLICT (symbol) DO UPDATE SET 
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    last_price = EXCLUDED.last_price,
    updated_at = now();
