-- seeds.sql
-- Dados iniciais para simulação abrangente da B3 com mais de 150 ativos

-- 1. Inserir configurações do sistema
INSERT INTO public.system_config (key, value) VALUES
('market_status', 'open'),
('sell_commission', '0.00025')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 2. Inserir cotações iniciais de ~160 ativos da B3 (Ações, FIIs e ETFs)
INSERT INTO public.assets (symbol, name, type, last_price, updated_at) VALUES
-- Ações (B3 - Ações Ordinárias e Preferenciais)
('AALR3', 'Alliança Saúde e Participações S.A.', 'acao', 22.50, now()),
('ABEV3', 'Ambev S.A.', 'acao', 12.50, now()),
('AERI3', 'Aeris Indústria e Comércio de Equipamentos S.A.', 'acao', 1.20, now()),
('ALOS3', 'Allos S.A.', 'acao', 22.10, now()),
('ALPA4', 'Alpargatas S.A.', 'acao', 9.20, now()),
('AMBP3', 'Ambipar Participações e Empreendimentos S.A.', 'acao', 18.40, now()),
('AMER3', 'Lojas Americanas S.A.', 'acao', 0.50, now()),
('ARZZ3', 'Arezzo Indústria e Comércio S.A.', 'acao', 58.40, now()),
('ASAI3', 'Sendas Distribuidora S.A. - Assaí', 'acao', 13.10, now()),
('AURE3', 'Auren Energia S.A.', 'acao', 13.20, now()),
('AZUL4', 'Azul S.A.', 'acao', 11.80, now()),
('B3SA3', 'B3 S.A. - Brasil, Bolsa, Balcão', 'acao', 12.20, now()),
('BBAS3', 'Banco do Brasil S.A.', 'acao', 27.50, now()),
('BBDC3', 'Banco Bradesco S.A. Ord', 'acao', 12.80, now()),
('BBDC4', 'Banco Bradesco S.A. Pref', 'acao', 14.50, now()),
('BBSE3', 'BB Seguridade Participações S.A.', 'acao', 33.10, now()),
('BEEF3', 'Minerva S.A.', 'acao', 7.40, now()),
('BHIA3', 'Casas Bahia Grupo S.A.', 'acao', 6.80, now()),
('BPAC11', 'Banco BTG Pactual S.A.', 'acao', 36.80, now()),
('BPAN4', 'Banco Pan S.A.', 'acao', 8.20, now()),
('BRAP4', 'Bradespar S.A.', 'acao', 20.30, now()),
('BRFS3', 'BRF S.A.', 'acao', 15.60, now()),
('BRKM5', 'Braskem S.A.', 'acao', 19.80, now()),
('BRSR6', 'Banco do Estado do Rio Grande do Sul S.A.', 'acao', 12.40, now()),
('CAML3', 'Camil Alimentos S.A.', 'acao', 9.10, now()),
('CBAV3', 'Companhia Brasileira de Alumínio', 'acao', 4.80, now()),
('CCRO3', 'CCR S.A.', 'acao', 13.40, now()),
('CEAB3', 'C&A Modas S.A.', 'acao', 7.50, now()),
('CMIG4', 'Companhia Energética de Minas Gerais Pref', 'acao', 11.20, now()),
('COGN3', 'Cogna Educação S.A.', 'acao', 2.30, now()),
('CPFE3', 'CPFL Energia S.A.', 'acao', 35.40, now()),
('CPLE6', 'Companhia Paranaense de Energia Pref', 'acao', 9.80, now()),
('CRFB3', 'Carrefour Brasil S.A.', 'acao', 10.90, now()),
('CSAN3', 'Cosan S.A.', 'acao', 15.20, now()),
('CSNA3', 'Companhia Siderúrgica Nacional', 'acao', 14.80, now()),
('CURY3', 'Cury Construtora e Incorporadora S.A.', 'acao', 18.20, now()),
('CYRE3', 'Cyrela Brazil Realty S.A.', 'acao', 21.50, now()),
('DIRR3', 'Direcional Engenharia S.A.', 'acao', 22.40, now()),
('DXCO3', 'Dexco S.A.', 'acao', 7.80, now()),
('ECOR3', 'EcoRodovias Infraestrutura e Logística S.A.', 'acao', 7.10, now()),
('EGIE3', 'Engie Brasil Energia S.A.', 'acao', 42.10, now()),
('ELET3', 'Centrais Elétricas Brasileiras S.A. Ord', 'acao', 38.50, now()),
('ELET6', 'Centrais Elétricas Brasileiras Pref', 'acao', 44.20, now()),
('EMBR3', 'Embraer S.A.', 'acao', 24.10, now()),
('ENEV3', 'Eneva S.A.', 'acao', 12.80, now()),
('ENGI11', 'Energisa S.A.', 'acao', 48.50, now()),
('EQTL3', 'Equatorial Energia S.A.', 'acao', 31.20, now()),
('EVEN3', 'Even Construtora e Incorporadora S.A.', 'acao', 6.40, now()),
('EZTC3', 'EZTEC Empreendimentos e Participações S.A.', 'acao', 15.80, now()),
('FESA4', 'Ferbasa S.A. Pref', 'acao', 38.20, now()),
('FLRY3', 'Fleury S.A.', 'acao', 16.20, now()),
('GGBR4', 'Gerdau S.A.', 'acao', 21.50, now()),
('GOAU4', 'Metalúrgica Gerdau S.A.', 'acao', 10.40, now()),
('GOLL4', 'Gol Linhas Aéreas Inteligentes S.A.', 'acao', 2.80, now()),
('GRND3', 'Grendene S.A.', 'acao', 6.90, now()),
('GUAR3', 'Guararapes Confecções S.A.', 'acao', 7.20, now()),
('HAPV3', 'Hapvida Participações e Investimentos S.A.', 'acao', 3.90, now()),
('HBSA3', 'Hidrovias do Brasil S.A.', 'acao', 3.40, now()),
('HYPE3', 'Hypera S.A.', 'acao', 34.50, now()),
('IGTI11', 'Iguatemi S.A.', 'acao', 22.80, now()),
('INTB3', 'Intelbras S.A.', 'acao', 22.10, now()),
('IRBR3', 'IRB - Brasil Resseguros S.A.', 'acao', 39.50, now()),
('ITSA4', 'Itaúsa S.A.', 'acao', 9.80, now()),
('ITUB4', 'Itaú Unibanco Holding S.A.', 'acao', 32.80, now()),
('JBSS32', 'JBS S.A.', 'acao', 32.10, now()),
('JHSF3', 'JHSF Participações S.A.', 'acao', 4.50, now()),
('KEPL3', 'Kepler Weber S.A.', 'acao', 10.80, now()),
('KLBN11', 'Klabin S.A.', 'acao', 21.90, now()),
('LREN3', 'Lojas Renner S.A.', 'acao', 16.50, now()),
('LWSA3', 'Locaweb Serviços de Internet S.A.', 'acao', 5.80, now()),
('MDIA3', 'M. Dias Branco S.A.', 'acao', 36.20, now()),
('MGLU3', 'Magazine Luiza S.A.', 'acao', 2.10, now()),
('MOVI3', 'Movida Participações S.A.', 'acao', 7.90, now()),
('MRFG3', 'Marfrig Global Foods S.A.', 'acao', 9.50, now()),
('MRVE3', 'MRV Engenharia e Participações S.A.', 'acao', 7.20, now()),
('MULT3', 'Multiplan Empreendimentos Imobiliários S.A.', 'acao', 24.80, now()),
('MYPK3', 'Iochpe Maxion S.A.', 'acao', 12.80, now()),
('NEOE3', 'Neoenergia S.A.', 'acao', 19.50, now()),
('NTCO3', 'Natura &Co Holding S.A.', 'acao', 15.90, now()),
('ODPV3', 'Odontoprev S.A.', 'acao', 11.80, now()),
('ONCO3', 'Instituto de Oncologia S.A.', 'acao', 6.80, now()),
('ORVR3', 'Orizon Valorização de Resíduos S.A.', 'acao', 38.50, now()),
('PCAR3', 'Companhia Brasileira de Distribuição - Pão de Açúcar', 'acao', 3.80, now()),
('PETR3', 'Petróleo Brasileiro S.A. Ord', 'acao', 40.50, now()),
('PETR4', 'Petróleo Brasileiro S.A. Pref', 'acao', 42.09, now()),
('PGMN3', 'Empreendimentos Pague Menos S.A.', 'acao', 2.90, now()),
('PLPL3', 'Plano & Plano Desenvolvimento Imobiliário S.A.', 'acao', 10.80, now()),
('POMO4', 'Marcopolo S.A. Pref', 'acao', 6.50, now()),
('PORT3', 'Wilson Sons S.A.', 'acao', 15.20, now()),
('POSI3', 'Positivo Tecnologia S.A.', 'acao', 8.20, now()),
('PRIO3', 'PetroRio S.A.', 'acao', 44.50, now()),
('PSSA3', 'Porto Seguro S.A.', 'acao', 28.50, now()),
('RADL3', 'Raia Drogasil S.A.', 'acao', 26.20, now()),
('RAIZ4', 'Raízen S.A.', 'acao', 3.60, now()),
('RAPT4', 'Randon S.A. Pref', 'acao', 11.80, now()),
('RECV3', 'PetroReconcavo S.A.', 'acao', 21.10, now()),
('RENT3', 'Localiza Rent a Car S.A.', 'acao', 58.40, now()),
('ROMI3', 'Indústrias Romi S.A.', 'acao', 11.40, now()),
('RRRP3', '3R Petroleum Óleo e Gás S.A.', 'acao', 27.50, now()),
('RUMO3', 'Rumo S.A.', 'acao', 22.40, now()),
('SANB11', 'Banco Santander (Brasil) S.A.', 'acao', 28.50, now()),
('SBSP3', 'Companhia de Saneamento Básico do Estado de SP', 'acao', 78.20, now()),
('SEQL3', 'Sequoia Logística e Transportes S.A.', 'acao', 0.80, now()),
('SIMH3', 'Simpar S.A.', 'acao', 7.40, now()),
('SLCE3', 'SLC Agrícola S.A.', 'acao', 19.10, now()),
('SMTO3', 'São Martinho S.A.', 'acao', 29.50, now()),
('STBP3', 'Santos Brasil Participações S.A.', 'acao', 13.80, now()),
('SUZB3', 'Suzano S.A.', 'acao', 56.40, now()),
('TAEE11', 'Transmissora Aliança de Energia Elétrica S.A.', 'acao', 35.80, now()),
('TASA4', 'Taurus Armas S.A. Pref', 'acao', 14.20, now()),
('TEND3', 'Construtora Tenda S.A.', 'acao', 10.40, now()),
('TIMS3', 'TIM S.A.', 'acao', 17.20, now()),
('TOTS3', 'Totvs S.A.', 'acao', 30.10, now()),
('TRPL4', 'CTEEP - Companhia de Transmissão de Energia Pref', 'acao', 25.10, now()),
('TTEN3', '3tentos Agroindustrial S.A.', 'acao', 11.20, now()),
('TXRX4', 'Teka-Tecelagem Kuehnrich S.A.', 'acao', 2.80, now()),
('UGPA3', 'Ultrapar Participações S.A.', 'acao', 26.40, now()),
('UNIP6', 'Unipar Carbocloro S.A.', 'acao', 72.50, now()),
('USIM5', 'Usinas Siderúrgicas de Minas Gerais Pref', 'acao', 8.20, now()),
('VALE3', 'Vale S.A.', 'acao', 62.10, now()),
('VIVA3', 'Vivara Participações S.A.', 'acao', 24.50, now()),
('VIVT3', 'Telefônica Brasil S.A.', 'acao', 51.50, now()),
('VLID3', 'Valid Soluções S.A.', 'acao', 16.20, now()),
('WEGE3', 'WEG S.A.', 'acao', 38.50, now()),
('YDUQ3', 'YDUQS Participações S.A.', 'acao', 16.80, now()),
('ZAMP3', 'Zamp S.A. (Burger King Brasil)', 'acao', 3.80, now()),

-- FIIs (Fundos Imobiliários de Alta Liquidez)
('MXRF11', 'Maxi Renda FII', 'fii', 10.15, now()),
('HGLG11', 'CSHG Logística FII', 'fii', 165.00, now()),
('ALZR11', 'Alianza Trust Renda Imobiliária FII', 'fii', 115.00, now()),
('HGRU11', 'CSHG Renda Urbana FII', 'fii', 125.00, now()),
('XPLG11', 'XP Log FII', 'fii', 108.50, now()),
('XPML11', 'XP Malls FII', 'fii', 112.40, now()),
('KNIP11', 'Kinea Índices de Preços FII', 'fii', 98.20, now()),
('KNCR11', 'Kinea Rendimentos Imobiliários FII', 'fii', 102.50, now()),
('HFOF11', 'Hedge Top FOFII FII', 'fii', 74.50, now()),
('VISC11', 'Vinci Shopping Centers FII', 'fii', 118.20, now()),
('BRCO11', 'Bresco Logística FII', 'fii', 122.50, now()),
('MALL11', 'Malls Brasil Plural FII', 'fii', 114.10, now()),
('BTLG11', 'BTG Pactual Logística FII', 'fii', 102.80, now()),
('PVBI11', 'VBI Prime Offices FII', 'fii', 98.40, now()),
('JSRE11', 'JS Real Estate Multigestão FII', 'fii', 72.10, now()),
('RECR11', 'FII Rec Recebíveis Imobiliários', 'fii', 82.50, now()),
('HGCR11', 'CSHG Recebíveis Imobiliários FII', 'fii', 104.20, now()),
('CPTS11', 'Capitânia Securities II FII', 'fii', 8.20, now()),
('TGAR11', 'TG Ativa Real FII', 'fii', 121.50, now()),
('IRDM11', 'Iridium Recebíveis Imobiliários FII', 'fii', 78.40, now()),
('KNSC11', 'Kinea Recebíveis Imobiliários FII', 'fii', 89.20, now()),
('VCJR11', 'Vectis Juros Real FII', 'fii', 92.50, now()),
('VRTA11', 'Fator Verità FII', 'fii', 88.40, now()),
('VGIR11', 'Valora REIII FII', 'fii', 9.60, now()),
('BTAL11', 'BTG Pactual Agro Logística FII', 'fii', 78.50, now()),
('VINO11', 'Vinci Oficinas FII', 'fii', 7.80, now()),

-- ETFs (Fundos de Índice e BDRs de Ações Globais)
('BOVA11', 'iShares Ibovespa Fundo de Índice', 'etf', 122.00, now()),
('IVVB11', 'iShares S&P 500 Fundo de Índice BDR', 'etf', 280.00, now()),
('SMAL11', 'iShares BM&FBOVESPA Small Cap FII', 'etf', 105.40, now()),
('XINA11', 'Trend China MSCI Fundo de Índice', 'etf', 6.20, now()),
('HASH11', 'Hashdex Nasdaq Crypto Index ETF', 'etf', 48.50, now()),
('QBTC11', 'QR Bitcoin ETF', 'etf', 16.80, now()),
('QETH11', 'QR Ether ETF', 'etf', 8.50, now()),
('DIVO11', 'Itau Ibovespa Div/IDIV Fundo de Índice', 'etf', 84.10, now()),
('GOLD11', 'Trend Ouro Fundo de Índice', 'etf', 11.20, now()),
('SPXI11', 'Itau S&P 500 Fundo de Índice BDR', 'etf', 290.50, now())
ON CONFLICT (symbol) DO UPDATE SET 
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    last_price = EXCLUDED.last_price,
    updated_at = now();
